(ns codenames.constants.ui-idents)

(def app-state                ::app-state)
(def routes-scale-factor      ::routes-scale-factor)
(def fullscreen-view          ::fullscreen-view)
(def main-popover             ::main-popover)
(def modal-dialog             ::modal-dialog)
(def login-window             ::login-window)
(def server-events            ::server-events)
(def transaction-log-handler  ::transaction-log-handler)
