(ns codenames.constants.ui-tabs)

(def pregame       ::pre-game)
(def leader-board  ::leader-board)
(def game          ::game)
(def game-board    ::game-board)
(def score-board   ::score-board)
(def player-board  ::player-board)
(def blue-team-tab ::blue-team-tab)
(def red-team-tab  ::red-team-tab)
